added check to gearmand init script if its possible to execute commands as user

diff --git a/extras/gearmand-init.in b/extras/gearmand-init.in
--- a/extras/gearmand-init.in
+++ b/extras/gearmand-init.in
@@ -70,8 +70,14 @@ case "$1" in
             exit 0;
         fi
 
-        CMD="$DAEMON -p $PORT -P $PIDFILE $OPTIONS --log-file=$LOGFILE -v -v --listen=$LISTEN"
+        CMD="$DAEMON -p $PORT -P $PIDFILE $OPTIONS --log-file=$LOGFILE -v -v --listen=$LISTEN > $LOGFILE 2>&1"
         if [ "$WHO" = "root" ]; then
+            # try to exec commands as user
+            su - $USER -c /bin/true
+            if [ $? -ne 0 ]; then
+                echo "cannot exec commands as user $USER, make sure user has a valid shell"
+                exit 1;
+            fi
             su - $USER -c  "$CMD"
         else
             $CMD
