use nc or netcat for gracefull stop

diff --git a/extras/gearmand-init.in b/extras/gearmand-init.in
--- a/extras/gearmand-init.in
+++ b/extras/gearmand-init.in
@@ -20,6 +20,11 @@ PIDFILE=/var/run/gearmand.pid
 LOGFILE=/var/log/gearmand.log
 USER=%USER%
 GRACEFUL_SHUTDOWN_TIME=30
+for f in /usr/bin/netcat /usr/bin/nc; do
+  if [ -x $f ]; then 
+    NC=$f
+  fi
+done
 
 function get_status() {
         pid=`cat $PIDFILE 2>/dev/null`
@@ -89,21 +94,23 @@ case "$1" in
             echo ". Not running."
         else
             # do a graceful shutdown
-            echo -n " gracefully "
-            echo "shutdown graceful" | nc -q 1 $LISTEN $PORT
-            x=$GRACEFUL_SHUTDOWN_TIME
-            while [ $x -gt 0 ]; do
-                echo -n "."
-                ps -p $pid > /dev/null 2>&1 && sleep 1 || x=0;
-                let "x=x-1"
-            done
+            if [ ! -z $NC ]; then
+                echo -n " gracefully "
+                echo "shutdown graceful" | $NC -w 1 $LISTEN $PORT
+                x=$GRACEFUL_SHUTDOWN_TIME
+                while [ $x -gt 0 ]; do
+                    echo -n "."
+                    ps -p $pid > /dev/null 2>&1 && sleep 1 || x=0;
+                    let "x=x-1"
+                done
 
-            ps -p $pid > /dev/null 2>&1;
-            if [ $? -ne 0 ]; then
-                echo "done"
-                exit 0;
-            else
-                echo "failed"
+                ps -p $pid > /dev/null 2>&1;
+                if [ $? -ne 0 ]; then
+                    echo "done"
+                    exit 0;
+                else
+                    echo "failed"
+                fi
             fi
 
             # kill if still running
